name: Release-Notes-Preview

on:
  pull_request:
    branches: [ master ]
  issue_comment:
    types: [ edited ]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow --tags
    - uses: docker://decathlon/release-notes-generator-action:2.0.1
      with:
        releaseBranch: master
      env:
        GITHUB_PR_USERNAME: ${{ github.actor }}
        OUTPUT_FOLDER: release_notes  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
